import { useEffect, useState } from "react";
import { Feather } from "@expo/vector-icons";
import { router } from "expo-router";
import { Alert, Image, ImageBackground, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { DashboardSummary, getAdminDashboard } from "../../src/lib/supabase";

const background = require("../../assets/arriere_plan_admin.png");
const logo = require("../../assets/logo-removebg-preview.png");
const money = (value: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "XOF", maximumFractionDigits: 0 }).format(value);
const soon = () => Alert.alert("Bientôt disponible", "Cette fonctionnalité arrive prochainement.");

export default function AdminDashboard() {
  const [data, setData] = useState<DashboardSummary | null>(null); const [error, setError] = useState(false);
  useEffect(() => { void getAdminDashboard().then(setData).catch(() => setError(true)); }, []);
  if (!data && !error) return <View style={styles.center}><Text>Chargement du tableau de bord…</Text></View>;
  if (error || !data) return <View style={styles.center}><Text>Impossible de charger le tableau de bord.</Text></View>;
  const cards = [["users","Total membres",String(data.totalMembers),"Voir les membres"],["calendar","Total à jour",String(data.membersPaid),"Cotisations réglées"],["clock","Total en retard",String(data.membersLate),"À relancer"],["handshake","Total droit d’adhésion",money(data.totalDue),"Montant dû"],["file-text","Total cotisation mensuelle",money(data.totalCollected),"Recettes"],["wallet","Total couverture ou dépense",money(data.totalOutstanding),"Solde"]] as const;
  return <ImageBackground source={background} style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.actions}><Pressable style={styles.action} onPress={soon}><Feather name="volume-2" size={25} color="#102B3D" /><Text>Événements</Text></Pressable><Image source={logo} style={styles.logo}/><Pressable style={styles.action} onPress={soon}><Feather name="settings" size={25} color="#102B3D" /><Text>Paramètres</Text></Pressable></View>
    <Text style={styles.hello}>Bonjour, Admin</Text><Text style={styles.title}>Tableau de bord</Text><Text style={styles.subtitle}>Voici un aperçu de l’activité de {data.organizationName}.</Text>
    <View style={styles.grid}>{cards.map(([icon,title,value,caption], index) => <Pressable key={title} style={styles.card} onPress={index === 0 ? soon : undefined}><View style={styles.icon}><Feather name={icon as never} size={24} color="#00A99D" /></View><Text style={styles.cardTitle}>{title}</Text><Text style={styles.value}>{value}</Text><Text style={styles.caption}>{caption}</Text></Pressable>)}</View>
    <Pressable style={styles.requests} onPress={() => router.push("/(admin)/membership-requests")}><Text style={styles.requestsText}>Gérer les demandes d’adhésion</Text><Feather name="arrow-right" size={20} color="#FFF" /></Pressable>
    <View style={styles.panel}><View style={styles.panelHead}><Text style={styles.panelTitle}>Graphique évolution des cotisations</Text><Text style={styles.period}>6 derniers mois⌄</Text></View><View style={styles.graph}><Feather name="bar-chart-2" size={42} color="#00A99D" /><Text style={styles.emptyTitle}>Module Finances bientôt disponible</Text><Text style={styles.emptyText}>L’évolution mensuelle apparaîtra ici.</Text></View></View>
    <View style={styles.panel}><View style={styles.panelHead}><Text style={styles.panelTitle}>Dernières transactions</Text><Pressable onPress={soon}><Text style={styles.link}>Voir tout  →</Text></Pressable></View><View style={styles.transaction}><Feather name="activity" size={25} color="#00A99D" /><View><Text style={styles.emptyTitle}>Aucune transaction</Text><Text style={styles.emptyText}>Le module Finances sera bientôt disponible.</Text></View></View></View>
    <View style={styles.nav}><Text style={styles.active}>⌂{`\n`}Tableau de bord</Text><Pressable onPress={soon}><Text style={styles.navText}>♧{`\n`}Membres</Text></Pressable><Pressable onPress={soon}><Text style={styles.navText}>♙{`\n`}Finances</Text></Pressable></View>
  </ScrollView></ImageBackground>;
}
const styles=StyleSheet.create({page:{flex:1},content:{gap:14,padding:20,paddingTop:52},center:{alignItems:"center",flex:1,justifyContent:"center"},actions:{alignItems:"center",flexDirection:"row",justifyContent:"space-between"},action:{alignItems:"center",gap:6},logo:{height:105,resizeMode:"contain",width:105},hello:{color:"#65758A",marginTop:22},title:{color:"#102B3D",fontSize:31,fontWeight:"800"},subtitle:{color:"#65758A",fontSize:16},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{backgroundColor:"rgba(255,255,255,.96)",borderRadius:18,elevation:2,minHeight:160,padding:14,width:"31%"},icon:{alignItems:"center",backgroundColor:"#E1F7F1",borderRadius:30,height:52,justifyContent:"center",width:52},cardTitle:{color:"#102B3D",fontSize:13,fontWeight:"700",marginTop:12},value:{color:"#00A99D",fontSize:17,fontWeight:"800",marginTop:7},caption:{color:"#65758A",fontSize:11,marginTop:5},requests:{alignItems:"center",backgroundColor:"#00A99D",borderRadius:14,flexDirection:"row",justifyContent:"space-between",padding:17},requestsText:{color:"#FFF",fontWeight:"800"},panel:{backgroundColor:"rgba(255,255,255,.96)",borderRadius:18,padding:17},panelHead:{alignItems:"center",flexDirection:"row",justifyContent:"space-between"},panelTitle:{color:"#102B3D",fontSize:18,fontWeight:"800"},period:{backgroundColor:"#EFF4F4",borderRadius:10,color:"#65758A",padding:8},graph:{alignItems:"center",gap:8,minHeight:165,justifyContent:"center"},emptyTitle:{color:"#102B3D",fontWeight:"700"},emptyText:{color:"#65758A",fontSize:12,textAlign:"center"},transaction:{alignItems:"center",flexDirection:"row",gap:12,minHeight:90},link:{color:"#00A99D",fontWeight:"700"},nav:{backgroundColor:"#FFF",borderRadius:18,flexDirection:"row",justifyContent:"space-around",padding:17},active:{color:"#00A99D",fontWeight:"800",textAlign:"center"},navText:{color:"#65758A",textAlign:"center"}});
