import { useEffect, useState } from "react";
import { Feather } from "@expo/vector-icons";
import { router } from "expo-router";
import { ImageBackground, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { DashboardSummary, getAdminDashboard } from "../../src/lib/supabase";

const money = (value: number) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "XOF", maximumFractionDigits: 0 }).format(value);
export default function AdminDashboard() {
  const [data, setData] = useState<DashboardSummary | null>(null); const [error, setError] = useState(false);
  useEffect(() => { void getAdminDashboard().then(setData).catch(() => setError(true)); }, []);
  if (!data && !error) return <View style={styles.center}><Text>Chargement du tableau de bord…</Text></View>;
  if (error || !data) return <View style={styles.center}><Text>Impossible de charger le tableau de bord.</Text></View>;
  const cards = [["users", "Total membres", String(data.totalMembers)], ["check-circle", "Total à jour", String(data.membersPaid)], ["clock", "Total en retard", String(data.membersLate)], ["handshake", "Total cotisation", money(data.totalDue)], ["dollar-sign", "Montant encaissé", money(data.totalCollected)], ["wallet", "Reste à encaisser", money(data.totalOutstanding)]] as const;
  return <ImageBackground source={require("../../../../maquette/arriere_plan_admin.png")} style={styles.page}><ScrollView contentContainerStyle={styles.content}><View style={styles.top}><Text style={styles.event}>Événements</Text><Feather name="settings" size={25} color="#102B3D" /></View><Text style={styles.hello}>Bonjour, Admin</Text><Text style={styles.title}>Tableau de bord</Text><Text style={styles.subtitle}>{data.organizationName}</Text><View style={styles.grid}>{cards.map(([icon, label, value]) => <View key={label} style={styles.card}><Feather name={icon as never} size={25} color="#00A99D" /><Text style={styles.cardTitle}>{label}</Text><Text style={styles.value}>{value}</Text></View>)}</View><Pressable style={styles.request} onPress={() => router.push("/(admin)/membership-requests")}><Text style={styles.requestText}>Gérer les demandes d’adhésion</Text><Feather name="arrow-right" size={20} color="#FFF" /></Pressable><View style={styles.future}><Text style={styles.futureTitle}>Graphique et transactions</Text><Text style={styles.futureText}>Module Finances bientôt disponible</Text></View><View style={styles.nav}><Text style={styles.active}>⌂  Tableau de bord</Text><Text>Membres</Text><Text>Finances</Text></View></ScrollView></ImageBackground>;
}
const styles = StyleSheet.create({ page:{flex:1},content:{padding:22,paddingTop:58,gap:14},center:{alignItems:"center",flex:1,justifyContent:"center",padding:24},top:{flexDirection:"row",justifyContent:"space-between"},event:{color:"#102B3D",fontWeight:"700"},hello:{color:"#65758A",marginTop:32},title:{color:"#102B3D",fontSize:31,fontWeight:"800"},subtitle:{color:"#65758A",fontSize:16},grid:{flexDirection:"row",flexWrap:"wrap",gap:10},card:{backgroundColor:"rgba(255,255,255,.94)",borderRadius:18,elevation:2,minHeight:130,padding:16,width:"48%"},cardTitle:{color:"#102B3D",fontWeight:"700",marginTop:14},value:{color:"#00A99D",fontSize:21,fontWeight:"800",marginTop:7},request:{alignItems:"center",backgroundColor:"#00A99D",borderRadius:14,flexDirection:"row",justifyContent:"space-between",padding:17},requestText:{color:"#FFF",fontWeight:"800"},future:{backgroundColor:"rgba(255,255,255,.94)",borderRadius:18,padding:20},futureTitle:{color:"#102B3D",fontSize:18,fontWeight:"800"},futureText:{color:"#65758A",marginTop:8},nav:{backgroundColor:"#FFF",borderRadius:18,flexDirection:"row",justifyContent:"space-between",padding:17},active:{color:"#00A99D",fontWeight:"800"} });
