import { router } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { createAdminFinanceAction, getFunctionErrorMessage, getMonthlyContributionSettings } from "../../../src/lib/supabase";
import { KeyboardSafeScreen } from "../../../src/components/keyboard-safe-screen";
export default function FinanceSettings() {
  const [monthlyAmount, setMonthlyAmount] = useState(""); const [dueDay, setDueDay] = useState("1"); const [error, setError] = useState(""); const [saved, setSaved] = useState(false); const [saving, setSaving] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; void getMonthlyContributionSettings().then(({ id }) => { if (!active) return; setMonthlyAmount(String(id.monthlyAmount)); setDueDay(String(id.dueDay)); }).catch(() => { if (active) setError("Impossible de charger les paramètres."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const save = async () => { const amount = Number(monthlyAmount); const day = Number(dueDay); if (!monthlyAmount.trim() || !Number.isFinite(amount) || amount < 0 || !Number.isInteger(day) || day < 1 || day > 28) return setError("Le montant doit être renseigné et le jour compris entre 1 et 28."); setSaving(true); setError(""); try { await createAdminFinanceAction({ action: "updateMonthlySettings", monthlyAmount: amount, dueDay: day }); setSaved(true); } catch (e) { setError((await getFunctionErrorMessage(e)) ?? "Impossible de mettre à jour les paramètres."); } finally { setSaving(false); } };
  return <KeyboardSafeScreen><View style={styles.page}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Retour</Text></Pressable><Text style={styles.title}>Paramètres financiers</Text><Text style={styles.subtitle}>Réservés aux administrateurs. Les membres disposent d’un accès en lecture seule.</Text>{loading ? <Text style={styles.hint}>Chargement des paramètres…</Text> : null}<Text style={styles.label}>Montant mensuel (XOF)</Text><TextInput value={monthlyAmount} onChangeText={setMonthlyAmount} keyboardType="decimal-pad" placeholder="Ex. 5000" style={styles.input} accessibilityLabel="Montant mensuel" /><Text style={styles.label}>Jour d’échéance (1 à 28)</Text><TextInput value={dueDay} onChangeText={setDueDay} keyboardType="number-pad" style={styles.input} accessibilityLabel="Jour d'échéance" /><Text style={styles.hint}>Le jour doit être compris entre 1 et 28.</Text>{error ? <Text style={styles.error}>{error}</Text> : null}{saved ? <Text style={styles.success}>Paramètres enregistrés.</Text> : null}<Pressable disabled={loading || saving} onPress={() => void save()} style={styles.submit}><Text style={styles.submitText}>{loading ? "Chargement…" : saving ? "Enregistrement…" : "Enregistrer"}</Text></Pressable></View></KeyboardSafeScreen>;
}
const styles = StyleSheet.create({ page: { backgroundColor: "#F7FBFA", flex: 1, gap: 12, padding: 22, paddingTop: 34 }, back: { color: "#007D74", fontWeight: "700" }, title: { color: "#102B3D", fontSize: 27, fontWeight: "800", marginTop: 12 }, subtitle: { color: "#65758A", lineHeight: 20, marginBottom: 18 }, label: { color: "#102B3D", fontSize: 13, fontWeight: "700" }, input: { backgroundColor: "#FFF", borderColor: "#DDE6E8", borderRadius: 12, borderWidth: 1, color: "#102B3D", minHeight: 50, padding: 12 }, hint: { color: "#65758A", fontSize: 12 }, error: { color: "#C75042", textAlign: "center" }, success: { color: "#007D74", textAlign: "center" }, submit: { alignItems: "center", backgroundColor: "#00A99D", borderRadius: 14, marginTop: 8, minHeight: 52, justifyContent: "center" }, submitText: { color: "#FFF", fontSize: 16, fontWeight: "800" } });
